//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntetyData : DbContext
    {
        public EntetyData()
            : base("EntetyData")
        {
            Database.SetInitializer(new DropCreateDatabaseIfModelChanges<EntetyData>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PersonDB>()
                  .Property(c => c.Id).IsRequired();

            modelBuilder.Entity<PersonDB>()
                .Property(e => e.fname).HasMaxLength(50);

            modelBuilder.Entity<PersonDB>()
                .Property(e => e.lname).HasMaxLength(30);

            modelBuilder.Entity<PersonDB>()
              .Property(e => e.age).IsOptional();
        }

        public virtual DbSet<PersonDB> PersonDB { get; set; }
    }
}
//public partial class EntityDBEntities : DbContext
//{
//    public EntityDBEntities()
//        : base("EntityDBEntities")
//    {
//        Database.SetInitializer(new DropCreateDatabaseIfModelChanges<EntityDBEntities>());
//    }

//    protected override void OnModelCreating(DbModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<EF_pers>()
//            .Property(c => c.Id).IsRequired();

//        modelBuilder.Entity<EF_pers>()
//            .Property(e => e.fname).HasMaxLength(50);

//        modelBuilder.Entity<EF_pers>()
//            .Property(e => e.lname).HasMaxLength(30);

//        modelBuilder.Entity<EF_pers>()
//            .Property(e => e.age).IsOptional();
//    }

//    public virtual DbSet<EF_pers> EF_pers { get; set; }
//}
